### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by NottCurious** [GreepTheSheep/node-trackmania.io#70]
```
<path>\node_modules\trackmania.io\src\client\Client.js:124
        resStr = str.replace(/\$T/g, '$t').replace(/\$Z/g, '$z');
                     ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Client.formatTMText (<path>\node_modules\trackmania.io\src\client\Client.js:124:22)
    at <path>\Routes\tm2020\player.js:27:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Tried with `38d07fe0-b39e-462b-85ef-8e870aeba429`.

player.js
```js
app.get('/tm2020/player/:id', async (req, res) => {
        const accId = req.params.id;

        const player = await client.players.get(accId);
        const data = player._data
        data.clubtagraw = client.formatTMText(data.clubtag)

        res.send(data)
    })
```

**Comment by GreepTheSheep** [comment]
The Club Tag on this account is undefined, meaning that the player does not have a club tag, so you need to add a check if the player does have a club tag

So the proper method should be:
```js
app.get('/tm2020/player/:id', async (req, res) => {
        const accId = req.params.id;

        const player = await client.players.get(accId);
        const data = player._data
        if (data.clubtag) data.clubtagraw = client.formatTMText(data.clubtag)

        res.send(data)
    })
```

**Comment by NottCurious** [comment]
my bad, thank you
